apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-sync
  namespace: argocd
spec:
  project: default

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: apps/secrets-sync
    helm:
      valueFiles:
        - values-local.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-sync

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
