apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
  labels:
    domain: platform
    subdomain: secrets
spec:
  project: platform

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: platform/scaleway/secrets
    helm:
      parameters:
        - name: revision
          value: {{ .Values.revision }}
        - name: repoURL
          value: {{ .Values.repoURL }}

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
