apiVersion: v2
name: demo
description: Demo nginx application
type: application
version: 0.1.0
appVersion: "1.27"

dependencies:
  - name: sso-guard
    alias: auth
    version: 0.1.0
    repository: "file://../../../../charts/sso-guard"
    condition: auth.enabled
