apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  labels:
    domain: apps
spec:
  project: apps

  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.revision }}
    path: apps/demo
    helm:
      valueFiles:
        - values-scaleway.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
